erDiagram
    USERS {
        int id PK
        string username
        string email
        string image_path
        string password
        string remember_token
        timestamp created_at
        timestamp updated_at
    }
    SURATS {
        int id PK
        string nomor_surat
        enum jenis_surat
        date tanggal_surat
        string perihal
        int created_by_user_id FK
        string nama_lengkap_pegawai
        string nip_pegawai
        string pangkat_golongan_pegawai
        string jabatan_pegawai
        string bidang_seksi_pegawai
        enum status_pegawai
        string nama_lengkap_kepala_pegawai
        string nip_kepala_pegawai
        string jabatan_kepala_pegawai
        enum jenis_cuti
        date tanggal_mulai_cuti
        date tanggal_selesai_cuti
        text keterangan_cuti
        text dasar_hukum
        text tujuan_tugas
        string lokasi_tugas
        date tanggal_mulai_tugas
        date tanggal_selesai_tugas
        text tembusan
        timestamp created_at
        timestamp updated_at
    }
    PASSWORD_RESET_TOKENS {
        string email PK
        string token
        timestamp created_at
    }
    SESSIONS {
        string id PK
        int user_id FK
        string ip_address
        text user_agent
        longtext payload
        int last_activity
    }
