Project KemenagCuti {
  database_type: 'MySQL'
  Note: 'Database schema for Kemenag Cuti Application'
}

Table users {
  id integer [primary key, increment]
  username string [unique]
  email string [unique, null]
  image_path string [null]
  password string
  remember_token string [null]
  created_at timestamp
  updated_at timestamp
}

Table surats {
  id integer [primary key, increment]
  nomor_surat string [unique]
  jenis_surat enum('cuti', 'tugas')
  tanggal_surat date
  perihal string

  // Foreign Keys
  created_by_user_id integer [note: 'Operator yang membuat surat']

  // Snapshot Data Pegawai
  nama_lengkap_pegawai string [null]
  nip_pegawai string [null]
  pangkat_golongan_pegawai string [null]
  jabatan_pegawai string [null]
  bidang_seksi_pegawai string [null]
  status_pegawai enum('PNS', 'PPPK') [default: 'PNS']

  // Snapshot Data Penandatangan
  nama_lengkap_kepala_pegawai string [null]
  nip_kepala_pegawai string [null]
  jabatan_kepala_pegawai string [null]

  // Cuti Specific
  jenis_cuti enum('tahunan', 'sakit', 'melahirkan', 'alasan_penting', 'besar') [null]
  tanggal_mulai_cuti date [null]
  tanggal_selesai_cuti date [null]
  keterangan_cuti text [null]

  // Tugas Specific
  dasar_hukum text [null]
  tujuan_tugas text [null]
  lokasi_tugas string [null]
  tanggal_mulai_tugas date [null]
  tanggal_selesai_tugas date [null]

  tembusan text [null]
  created_at timestamp
  updated_at timestamp
}

Table password_reset_tokens {
  email string [primary key]
  token string
  created_at timestamp [null]
}

Table sessions {
  id string [primary key]
  user_id integer [null]
  ip_address string [null]
  user_agent text [null]
  payload longtext
  last_activity integer
}



Ref: surats.created_by_user_id > users.id [delete: cascade]
Ref: sessions.user_id > users.id
